#!/bin/bash
#SBATCH --job-name=02_bbduk
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/02_bbduk.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/02_bbduk.out"


# à la fin lancer un fastqc / multi qc pour checker la qualité à chaque étape
