#!/bin/bash
#SBATCH --job-name=02_bbduk
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/02_bbduk.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/02_bbduk.out"



ENTREE="/home/amartin3/01_concatenated_data/" #4 fichiers concaténés 
SORTIE="home/amartin3/02_bbduk" #résultats

mkdir -p "$SORTIE"

module load conda/4.12.0
source ~/.bashrc
conda activate bioinformatic

PHIX=/home/amartin3/bbmap/resources/phix174_ill.ref.fa.gz
BBDUK=/home/amartin3/bbmap/bbduk.sh

cd "$ENTREE"

#boucle sur tous les fichiers R1 
for r1_file in *_R1.fastq.gz; do

    # Déduire le nom du fichier R2 
    r2_file="${r1_file/_R1.fastq.gz/_R2.fastq.gz}"
    
    #vérifie que le R2 existe
    [[ ! -f "$r2_file" ]] && { echo "ERREUR: Fichier R2 manquant pour $r1_file" >&2; continue; }
    
    # Extraire le nom de base propre du fichier
    base_name="${r1_file%_R1.fastq.gz}"

 
    # Lancement de BBDuk
    $BBDUK -Xmx4g \ #4 Go 
        in1="$r1_file" \ #fichiers d'entrée R1 et R2
        in2="$r2_file" \ 
        out1=$OUTPUT/"clean_${r1_file}" \
        out2=$OUTPUT/"clean_${r2_file}" \
        ref=$PHIX \ #contaminant du séquençage
        ktrim=rl \ #quand un kmer match dans un read, lui et toutes les bases à droites sont supp
        k=23 \ #taille des kmer (d'ou ils viennent)
        mink=11 \ #chercher des kmer plus courts (entre 11 et 22)
        hdist=1 \ #distance de hamming (quantifie différentre entre 2 seq)
        tpe \ # trim both reads to the same length (au cas ou kmer détecté dans un seul read)
        tbo \ # trim adapters based on pair overlap detection (pourquoi?)
        minlen=25 \ #supprime reads plus courts que 25bp
        qtrim=r \ #Trim read ends to remove bases with quality below trimq (trim right side only)
        trimq=20 \
        stats="$OUTPUT/${base_name}_bbduk_stats.txt" #?



# à la fin lancer un fastqc / multi qc pour checker la qualité à chaque étape
