#!/bin/bash
#SBATCH --job-name=03_clumpify
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/03_clumpify.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/03_clumpify.out"



SORTIE="/home/amartin3/03_clumpify"

mkdir -p "$SORTIE"
