#!/bin/bash
#SBATCH --job-name=03_fastuniq
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/03_fastuniq.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/03_fastuniq.out"

ENTREE="/home/amartin3/02_bbduk"
SORTIE="/home/amartin3/03_fastuniq"

mkdir -p "$SORTIE"

module load conda/4.12.0
source ~/.bashrc
conda activate bioinformatic

cd "$ENTREE" || exit 1 # terminate a script  (an error has occurred)


#controle qualité à la fin 
