#!/bin/bash
#SBATCH --job-name=04_clumpify
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/04_clumpify.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/04_clumpify.out"


ENTREE="/home/amartin3/03_fastuniq"
SORTIE="/home/amartin3/04_clumpify"

module load conda/4.12.0
source ~/.bashrc
conda activate bioinformatic

CLUMPIFY=/home/amartin3/bbmap/clumpify.sh

#crée le dossier s'il n'existe pas
mkdir -p "$SORTIE"

#pour tous les fichiers R1 


#faire controle qualité 
