#!/bin/bash
#SBATCH --job-name=04_fastp 
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL 
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/04_fastp.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/04_fastp.out"



#activer environnement conda
module load conda/4.12.0
source ~/.bashrc
conda activate bioinformatic

