#!/bin/bash
#SBATCH --job-name=11_mapdamage_vitis_vinifera
#SBATCH --ntasks=1
#SBATCH -p smp
#SBATCH --mem=1000G
#SBATCH --mail-user=alexa.martin@inrae.fr
#SBATCH --mail-type=ALL
#SBATCH --error="/home/amartin3/CapoSagro_Alexa/00_scripts/11_mapdamage_vitis_vinifera.err"
#SBATCH --output="/home/amartin3/CapoSagro_Alexa/00_scripts/11_mapdamage_vitis_vinifera.out"


VITIS_DIR="/home/amartin3/12_mapdamage/sed6/Vitis_vinifera"

REF_FASTA="/home/amartin3/genomes/Vitis_vinifera.fna"

OUT_DIR="/home/amartin3/12_mapdamage_vitis_vinifera"


mkdir -p "$OUT_DIR"

# Chargement de l'environnement
module load conda/4.12.0
source ~/.bashrc
conda activate bioinformatic

echo "Début du traitement de la vigne (sed6) à $(date)"

#recuperation des fichiers bam
BAM_UNMERGED=$(ls ${VITIS_DIR}/*unmerged*.sorted.bam)
BAM_MERGED=$(ls ${VITIS_DIR}/*merged*.sorted.bam | grep -v "unmerged")

echo "Fichier Unmerged trouvé : $BAM_UNMERGED"
echo "Fichier Merged trouvé : $BAM_MERGED"


#concatenation des fichiers
echo "Conversion des BAMs en SAM"
samtools view -h "$BAM_UNMERGED" > "${OUT_DIR}/unmerged.sam"
samtools view "$BAM_MERGED" > "${OUT_DIR}/merged_no_header.sam"

echo "Concaténation des fichiers SAM avec cat..."
cat "${OUT_DIR}/unmerged.sam" "${OUT_DIR}/merged_no_header.sam" > "${OUT_DIR}/sed6_Vitis_vinifera_combined.sam"

echo "Conversion du SAM combiné en BAM trie"
samtools sort -o "${OUT_DIR}/sed6_Vitis_vinifera_combined.sorted.bam" "${OUT_DIR}/sed6_Vitis_vinifera_combined.sam"
samtools index "${OUT_DIR}/sed6_Vitis_vinifera_combined.sorted.bam"

#suppression des fichiers temporaires 
rm -f "${OUT_DIR}/unmerged.sam" "${OUT_DIR}/merged_no_header.sam" "${OUT_DIR}/sed6_Vitis_vinifera_combined.sam"


#lancement de mapdamage
echo "Lancement de mapDamage sur le BAM combiné..."
mapDamage -i "${OUT_DIR}/sed6_Vitis_vinifera_combined.sorted.bam" \
  -r "$REF_FASTA" \
  --folder "${OUT_DIR}/mapDamage_combined_results" \
  --no-stats

echo "Fin du script avec succès à $(date)"
